export type LIBColorValue =
  'color-neutral-white' |
  'color-neutral-lighter' |
  'color-neutral-light' |
  'color-neutral-base' |
  'color-neutral-dark' |
  'color-neutral-text' |
  'color-status-success-base' |
  'color-status-success-light' |
  'color-status-success-dark' |
  'color-status-error-base' |
  'color-status-error-light' |
  'color-status-error-dark' |
  'color-status-warning-base' |
  'color-status-warning-light' |
  'color-status-warning-dark' |
  'color-primary-base' |
  'color-primary-dark' |
  'color-primary-light' |
  'color-secondary-base' |
  'color-secondary-light' |
  'color-secondary-dark' |
  'color-10' |
  'color-20' |
  'color-30' |
  'color-40' |
  'color-50' |
  'color-60' |
  'color-70' |
  'color-80' |
  'color-90' |
  'color-100' |
  'color-120' |
  'color-140' |
  'color-160' |
  'color-180' |
  'color-05';

export type LIBTypeValue =
  'type-heading-1' |
  'type-heading-1-size' |
  'type-heading-1-weight' |
  'type-heading-1-b' |
  'type-heading-1-b-size' |
  'type-heading-1-b-weight' |
  'type-heading-2' |
  'type-heading-2-size' |
  'type-heading-2-weight' |
  'type-heading-2-b' |
  'type-heading-2-b-size' |
  'type-heading-2-b-weight' |
  'type-heading-3' |
  'type-heading-3-size' |
  'type-heading-3-weight' |
  'type-heading-3-b' |
  'type-heading-3-b-size' |
  'type-heading-3-b-weight' |
  'type-heading-4' |
  'type-heading-4-size' |
  'type-heading-4-weight' |
  'type-heading-5' |
  'type-heading-5-size' |
  'type-heading-5-weight' |
  'type-heading-5-b' |
  'type-heading-5-b-size' |
  'type-heading-5-b-weight' |
  'type-heading-6' |
  'type-heading-6-size' |
  'type-heading-6-weight' |
  'type-link' |
  'type-link-size' |
  'type-link-weight' |
  'type-label-bold' |
  'type-label-bold-size' |
  'type-label-bold-weight' |
  'type-label' |
  'type-label-size' |
  'type-label-weight' |
  'type-button' |
  'type-button-size' |
  'type-button-weight' |
  'type-caption' |
  'type-caption-size' |
  'type-caption-weight' |
  'type-body-1-semi-bold' |
  'type-body-1-semi-bold-size' |
  'type-body-1-semi-bold-weight' |
  'type-body-1-regular' |
  'type-body-1-regular-size' |
  'type-body-1-regular-weight' |
  'type-body-1-regular-underlined' |
  'type-body-1-regular-underlined-size' |
  'type-body-1-regular-underlined-weight' |
  'type-body-2-regular' |
  'type-body-2-regular-size' |
  'type-body-2-regular-weight' |
  'type-body-2-semi-bold' |
  'type-body-2-semi-bold-size' |
  'type-body-2-semi-bold-weight' |
  'type-body-2-regular-underlined' |
  'type-body-2-regular-underlined-size' |
  'type-body-2-regular-underlined-weight' |
  'type-subtitle-subtitle-2' |
  'type-subtitle-subtitle-2-size' |
  'type-subtitle-subtitle-2-weight' |
  'type-subtitle-subtitle-1' |
  'type-subtitle-subtitle-1-size' |
  'type-subtitle-subtitle-1-weight';

export type LIBSpacingValue =
  'spacing-col-0' |
  'spacing-col-0-3' |
  'spacing-col-0-4' |
  'spacing-col-0-6' |
  'spacing-col-0-8' |
  'spacing-col-0-9' |
  'spacing-col-1' |
  'spacing-col-1-3' |
  'spacing-col-1-4' |
  'spacing-col-1-6' |
  'spacing-col-1-8' |
  'spacing-col-1-9' |
  'spacing-col-2' |
  'spacing-col-2-3' |
  'spacing-col-2-4' |
  'spacing-col-2-6' |
  'spacing-col-2-8' |
  'spacing-col-2-9' |
  'spacing-col-3' |
  'spacing-col-3-3' |
  'spacing-col-3-4' |
  'spacing-col-3-6' |
  'spacing-col-3-8' |
  'spacing-col-3-9' |
  'spacing-col-4' |
  'spacing-col-5' |
  'spacing-col-6' |
  'spacing-col-7' |
  'spacing-col-8' |
  'spacing-col-9' |
  'spacing-col-10' |
  'spacing-col-11' |
  'spacing-col-12' |
  'spacing-colvw-0' |
  'spacing-colvw-0-3' |
  'spacing-colvw-0-4' |
  'spacing-colvw-0-6' |
  'spacing-colvw-0-8' |
  'spacing-colvw-0-9' |
  'spacing-colvw-1' |
  'spacing-colvw-1-3' |
  'spacing-colvw-1-4' |
  'spacing-colvw-1-6' |
  'spacing-colvw-1-8' |
  'spacing-colvw-1-9' |
  'spacing-colvw-2' |
  'spacing-colvw-2-3' |
  'spacing-colvw-2-4' |
  'spacing-colvw-2-6' |
  'spacing-colvw-2-8' |
  'spacing-colvw-2-9' |
  'spacing-colvw-3' |
  'spacing-colvw-3-3' |
  'spacing-colvw-3-4' |
  'spacing-colvw-3-6' |
  'spacing-colvw-3-8' |
  'spacing-colvw-3-9' |
  'spacing-colvw-4' |
  'spacing-colvw-5' |
  'spacing-colvw-6' |
  'spacing-colvw-7' |
  'spacing-colvw-8' |
  'spacing-colvw-9' |
  'spacing-colvw-10' |
  'spacing-colvw-11' |
  'spacing-colvw-12';

export type LIBValue =
  LIBColorValue |
  LIBTypeValue |
  LIBSpacingValue;
